### ISSUE TITLE
iOS7查看图片浏览器的实现出现白屏

### ISSUE THREAD

**Issue by 276023272** [gang544043963/LGPhotoBrowser#11]
iOS7查看图片浏览器的实现出现白屏，并且不能点击。还有拍照的时候按钮都不见了，请问是什么问题。

**Comment by 276023272** [comment]
里面获取size，直接使用view.width这种方式，还是使用view.frame.size.width

**Comment by gang544043963** [comment]
都一样的，有个分类（UIView+Layout）可以让view.width = view.frame.size.width。
