### ISSUE TITLE
navigationBar设置为不隐藏，页面下沉

### ISSUE THREAD

**Issue by q1992077** [gang544043963/LGPhotoBrowser#13]
我想保留navigationBar，但是不隐藏navigationBar的话，页面会整体下沉。要怎么设置才不会下沉呢？navigationBar.translucent = NO;navigationBar不透明。

**Comment by gang544043963** [comment]
translucent = YES;

**Comment by q1992077** [comment]
translucent = YES的话，上部又会被navigationBar挡住了
