### ISSUE TITLE
从图片选择器选择多张图片后预览进入图片浏览器滚动到最后一张图片后有问题

### ISSUE THREAD

**Issue by iccpeng** [gang544043963/LGPhotoBrowser#15]
从图片选择器选择多张图片后通过点击预览按钮进入图片浏览器滚动到最后一张图片,如果最后一张图片为全屏竖图的话,如果再有向后滚动的操作,当再向前滚动的时候将会出现无法滚动的情况,望作者检查一下.

**Comment by gang544043963** [comment]
手机型号和系统版本给我说一下。目前我这边的几个手机没发现这个问题

**Comment by IMCCP** [comment]
可能是模拟器的问题,真机上问题不大,再次感谢楼主.
