### ISSUE TITLE
内存使用率很高

### ISSUE THREAD

**Issue by taojeff** [gang544043963/LGPhotoBrowser#21]
博主，如果手机相册中照片很多的情况下载选择照片选择器在点击大图浏览情况下。不断的滑动切换相片很快内存会增上去从而导致奔溃闪退

**Comment by gang544043963** [comment]
感谢提issue，我会尽快处理

**Comment by HQL-yunyunyun** [comment]
@gang544043963 有没有一个比较好解决方式，我发现很多的 图片浏览器 都存在这样一个问题(系统的也是), 而且在查看 缩略图 的时候也存在这样的问题。

**Comment by gang544043963** [comment]
图片本来就是数据量较大的文件，耗内存正常。但是目前我还没有发现『快速增长导致崩溃』的现象。谁有好的解决方案欢迎贡献代码
