### ISSUE TITLE
从相册添加多张图片时，内存严重上涨

### ISSUE THREAD

**Issue by lyhczz** [gang544043963/LGPhotoBrowser#28]
调用LGPhotoAssets这个类的几个属性都会出现内存泄漏，应该是这句代码[[self.asset defaultRepresentation] fullScreenImage]的问题。我也不知道怎么解决

**Comment by gang544043963** [comment]
这个不是内存泄漏。调用的是系统方法，读取照片本来就耗内存，这个目前是解决不了的
