### ISSUE TITLE
拖到IOS11 里工程报错了

### ISSUE THREAD

**Issue by zjTek** [gang544043963/LGPhotoBrowser#30]
being linked (8.0)
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_LGPhotoPickerViewController", referenced from:
      objc-class-ref in NewCaledarController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by gang544043963** [comment]
单独编译应该没问题吧？我已经在iPhone X模拟器上试过了。
看错误提示应该是没有添加对应文件导致的，请看这篇博客：
http://blog.csdn.net/henk_kong/article/details/53022339

如果问题解决了记得反馈

**Comment by beforeold** [comment]
@zjTek  because u did not import LGPhoto property. try "xxx.h" => <....h>
