### ISSUE TITLE
滴滴滴，在不在

### ISSUE THREAD

**Issue by Affee** [gang544043963/LGPhotoBrowser#38]
if(self.callback){
        self.callback(self.images);
        AFLog(@"%@",self.images);
    }
这个返回的数据是(
    "<ZLCamera: 0x1c0431800>",
    "<ZLCamera: 0x1c042c320>",
    "<ZLCamera: 0x1c4420ba0>"
)
麻烦问下，这个self.images 怎么转成图片啊，这个数据不是图片，也不是nsdata，怎么转成图片

**Comment by Affee** [comment]
哦了 解决辣

**Comment by youngwifemoliy** [comment]
你好
这个回调返回的是一个`ZLCamera`类型的对象
具体可以查看`ZLCamera.h`这个文件
这个类型有`_thumbImage`和`_photoImage`两个`UIImage`属性提供选择

**Comment by Affee** [comment]
嗯，发完直接就解决了，忘记回复了， 三克油
