### ISSUE TITLE
-[UIView setHidden:] must be used from main thread only

### ISSUE THREAD

**Issue by chjsun** [gang544043963/LGPhotoBrowser#46]
![image](https://user-images.githubusercontent.com/13481443/39958918-6391ef76-563c-11e8-92e0-ec35bbea24e8.png)

![image](https://user-images.githubusercontent.com/13481443/39958928-712f93ea-563c-11e8-9630-e5e7b07a4e81.png)

**Comment by gang544043963** [comment]
感谢您的反馈，抽空修复一下。也希望你能提pull request来贡献代码
