### ISSUE TITLE
关于网络图片浏览器，怎么显示点击的图片，而不是都从第一张开始浏览

### ISSUE THREAD

**Issue by Alamoalone** [gang544043963/LGPhotoBrowser#9]
正在使用你的这个库，感觉很好，但是请告知我怎么解决如题的问题

**Comment by gang544043963** [comment]
设置currentIndexPath

**Comment by Alamoalone** [comment]
我传出来的tag是NsInteger,而这个是NSIndexPath

**Comment by Alamoalone** [comment]
已解决，谢谢

**Comment by chenqingxiao007** [comment]
@Alamoalone 设置currentIndexPath，弹出视图index不对

**Comment by cryboyofyu** [comment]
对啊，currentindexpath设置了不对，请问是取得  row  还是section   ，我的是collectionview放的图片

**Comment by gang544043963** [comment]
section,您可以参考从相册进入大图浏览的代码
- (void) setupPhotoBrowserInCasePreview:(BOOL)preview
                       CurrentIndexPath:(NSIndexPath *)indexPath
